# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Parameterised variational ansatz built on top of :mod:`pyqpanda3`.

The :class:`VariationalAnsatz` describes a hardware-efficient ansatz
:math:`|\\psi(\\boldsymbol\\theta)\\rangle = U(\\boldsymbol\\theta)|\\phi_0\\rangle`
as an ordered list of gates.  Parameterised Pauli rotations
:math:`R_P(\\theta)=\\exp(-i\\theta P/2)` are differentiated exactly through the
parameter-shift rule, which provides the wavefunction Jacobian needed by the
McLachlan variational principle.
"""

from __future__ import annotations

from typing import Callable, Iterable

import numpy as np
from pyqpanda3.core import (CPUQVM, QProg, CNOT, CZ, H, ISWAP, SWAP, RX, RY,
                            RZ, RXX, RYY, RZZ, RZX, S, T, TOFFOLI, X, Y, Z)

__all__ = ["VariationalAnsatz", "HardwareEfficientAnsatz"]


# Look-up table of parameterised rotation gates that obey the standard
# parameter-shift rule:  d/dtheta R(theta) = (R(theta+pi/2) -
# R(theta-pi/2)) / (2 sqrt(2))   (statevector form).  The key is the gate
# factory; the value is the Pauli axis the rotation is generated by, used here
# only for documentation / debugging.  Single- and two-qubit Pauli rotations
# are both supported.
_PARAM_GATES = {RX: "X", RY: "Y", RZ: "Z"}
_PARAM_GATES_2Q = {RZZ: "ZZ", RXX: "XX", RYY: "YY", RZX: "ZX"}


# Registry of all pyqpanda3 gate factories supported by ``add_gate``.  Storing
# gate factories by name keeps ``_gates`` picklable (pybind11 gate factories
# carry a PyCapsule that the standard pickler cannot serialise).
_GATE_REGISTRY: dict[str, Callable] = {
    "H": H, "X": X, "Y": Y, "Z": Z, "S": S, "T": T,
    "CNOT": CNOT, "CZ": CZ, "SWAP": SWAP, "ISWAP": ISWAP, "TOFFOLI": TOFFOLI,
    "RX": RX, "RY": RY, "RZ": RZ,
    "RXX": RXX, "RYY": RYY, "RZZ": RZZ, "RZX": RZX,
}


def _factory_name(factory: Callable) -> str:
    """Return the registry name of a gate factory."""
    try:
        return factory.__name__
    except AttributeError:
        return str(factory)


def _is_param_gate(factory: Callable) -> bool:
    """Return ``True`` if ``factory`` is a supported parameterised rotation."""
    return factory in _PARAM_GATES or factory in _PARAM_GATES_2Q


class VariationalAnsatz:
    """A flexible parameterised ansatz on top of :mod:`pyqpanda3`.

    The ansatz is constructed by pushing gates through :meth:`add_gate` and
    :meth:`add_layer`.  Each *parameterised* gate consumes one entry of the
    parameter vector ``theta`` while *static* gates (H, CNOT, ...) take no
    parameter.  The circuit is rebuilt with concrete parameter values every
    time :meth:`get_statevector` is called.

    Parameters
    ----------
    n_qubits : ``int``
        Number of qubits in the ansatz circuit.
    init_state : ``ndarray``, optional
        Initial wavefunction to be loaded before the parameterised gates are
        applied.  If ``None`` the all-zero state is used and an optional set of
        preparation gates (added by the user) defines the reference state.

    Examples
    --------
    >>> import numpy as np
    >>> from pyqpanda3.core import H, RY, RZ, CNOT
    >>> from pyqpanda_alg.LindbladMagnus.ansatz import VariationalAnsatz
    >>> ans = VariationalAnsatz(n_qubits=2)
    >>> ans.add_gate(H, 0)
    >>> ans.add_gate(RY, 0)        # theta[0]
    >>> ans.add_gate(RZ, 1)        # theta[1]
    >>> ans.add_gate(CNOT, (0, 1))
    >>> sv = ans.get_statevector(np.array([0.2, 0.4]))
    """

    def __init__(self, n_qubits: int, init_state: np.ndarray | None = None):
        if n_qubits <= 0:
            raise ValueError(f"n_qubits must be positive, got {n_qubits}")
        self.n_qubits = n_qubits
        self.init_state = init_state
        self._gates: list[tuple] = []
        self._param_count = 0
        self._qvm = CPUQVM()
        if init_state is not None:
            dim = 1 << n_qubits
            if init_state.shape not in ((dim,), (dim, 1)):
                raise ValueError(
                    f"init_state must have shape ({dim},) or ({dim}, 1), got "
                    f"{init_state.shape}")

    # ------------------------------------------------------------------ #
    #  Pickling support (CPUQVM is not picklable)                        #
    # ------------------------------------------------------------------ #
    def __getstate__(self) -> dict:
        """Exclude the non-picklable :class:`CPUQVM` from the state dict."""
        state = self.__dict__.copy()
        state["_qvm"] = None
        return state

    def __setstate__(self, state: dict) -> None:
        """Re-create a fresh :class:`CPUQVM` after unpickling."""
        self.__dict__.update(state)
        self._qvm = CPUQVM()

    def __repr__(self) -> str:
        cls = type(self).__name__
        return (f"{cls}(n_qubits={self.n_qubits}, "
                f"n_parameters={self.n_parameters}, "
                f"n_gates={len(self._gates)})")

    # ------------------------------------------------------------------ #
    #  Construction                                                       #
    # ------------------------------------------------------------------ #
    @property
    def n_parameters(self) -> int:
        """Number of variational parameters."""
        return self._param_count

    def add_gate(self, factory: Callable, qubits: int | tuple[int, ...],
                 param_index: int | None = None,
                 extra: float | None = None) -> "VariationalAnsatz":
        """Append a single gate to the ansatz.

        Parameters
        ----------
        factory : ``callable``
            A gate constructor from :mod:`pyqpanda3.core`, e.g. ``RX``, ``H``,
            ``CNOT``.  Parameterised rotations (``RX``/``RY``/``RZ`` and
            ``RZZ``/``RXX``/``RYY``) are detected automatically and consume one
            parameter.
        qubits : ``int`` or ``tuple`` of ``int``
            Qubit index (or tuple of indices) the gate acts on.
        param_index : ``int``, optional
            Explicit index of the variational parameter the gate should
            consume.  When ``None`` (the default) for a parameterised gate, the
            next free index is used automatically.
        extra : ``float``, optional
            Constant offset added to ``theta[param_index]`` before being passed
            to the gate.

        Return
        ----------
        self : :class:`VariationalAnsatz`
            Enables chaining of ``add_gate`` calls.
        """
        name = _factory_name(factory)
        if name not in _GATE_REGISTRY:
            raise ValueError(
                f"unsupported gate factory {factory!r}; supported gates are: "
                f"{sorted(_GATE_REGISTRY)}")
        if isinstance(qubits, int):
            qubits = (qubits,)
        else:
            qubits = tuple(qubits)
        if not all(0 <= q < self.n_qubits for q in qubits):
            raise ValueError(
                f"qubit indices {qubits} out of range for a "
                f"{self.n_qubits}-qubit ansatz (valid: 0..{self.n_qubits - 1})")
        if _is_param_gate(factory):
            if param_index is None:
                param_index = self._param_count
                self._param_count += 1
            elif param_index + 1 > self._param_count:
                self._param_count = param_index + 1
            self._gates.append(("param", name, qubits, param_index, extra))
        else:
            self._gates.append(("static", name, qubits, extra))
        return self

    def add_layer(self, gates: Iterable[tuple]) -> "VariationalAnsatz":
        """Append several gates described by ``(factory, qubits)`` tuples.

        Parameters
        ----------
        gates : iterable of ``(factory, qubits)`` or
                ``(factory, qubits, param_index)``
            Gates to append.  The ``param_index`` entry is optional and follows
            the convention of :meth:`add_gate`.

        Return
        ----------
        self : :class:`VariationalAnsatz`
        """
        for spec in gates:
            if len(spec) == 2:
                self.add_gate(spec[0], spec[1])
            elif len(spec) == 3:
                self.add_gate(spec[0], spec[1], spec[2])
            else:
                raise ValueError(
                    "each layer entry must be (factory, qubits[, param_index])")
        return self

    # ------------------------------------------------------------------ #
    #  Circuit assembly                                                  #
    # ------------------------------------------------------------------ #
    def to_qprog(self, theta: np.ndarray | None = None) -> QProg:
        """Build the :class:`~pyqpanda3.core.QProg` for ``theta``.

        Parameters
        ----------
        theta : ``ndarray``, optional
            Variational parameters.  Defaults to a zero vector so that the
            returned circuit prepares the reference state.

        Return
        ----------
        prog : :class:`~pyqpanda3.core.QProg`
            The concrete quantum program (can be drawn, transpiled, etc.).
        """
        if theta is None:
            theta = np.zeros(self._param_count)
        return self._build_prog(theta)

    def _build_prog(self, theta: np.ndarray) -> QProg:
        """Build the :class:`~pyqpanda3.core.QProg` corresponding to ``theta``."""
        theta = np.asarray(theta, dtype=float).reshape(-1)
        if theta.size != self._param_count:
            raise ValueError(
                f"theta has length {theta.size} but the ansatz expects "
                f"{self._param_count} parameters")
        prog = QProg()
        if self.init_state is not None:
            prog << _prepare_state_prog(self.init_state, self.n_qubits)
        for entry in self._gates:
            kind = entry[0]
            factory = _GATE_REGISTRY[entry[1]]
            qubits = entry[2]
            if kind == "param":
                _, _, _, idx, extra = entry
                angle = float(theta[idx])
                if extra is not None:
                    angle += float(extra)
                prog << factory(*qubits, angle)
            else:
                _, _, _, extra = entry
                if extra is None:
                    prog << factory(*qubits)
                else:
                    prog << factory(*qubits, extra)
        return prog

    # ------------------------------------------------------------------ #
    #  Evaluation                                                        #
    # ------------------------------------------------------------------ #
    def get_statevector(self, theta: np.ndarray) -> np.ndarray:
        """Return the (normalised) statevector produced by ``theta``.

        Parameters
        ----------
        theta : ``ndarray`` of shape ``(n_parameters,)``
            Variational parameters.

        Return
        ----------
        statevector : ``ndarray``
            Complex statevector of length ``2**n_qubits``.
        """
        prog = self._build_prog(theta)
        self._qvm.run(prog, shots=1)
        sv = np.asarray(self._qvm.result().get_state_vector(), dtype=complex)
        return sv.reshape(-1)

    def get_jacobian(self, theta: np.ndarray) -> np.ndarray:
        """Return the wavefunction Jacobian ``d|psi>/d theta_i``.

        Each Pauli rotation is differentiated exactly via the parameter-shift
        rule.  For :math:`R_P(\\theta)=\\exp(-i\\theta P/2)`,

        .. math::
            \\frac{\\partial}{\\partial\\theta_i}|\\psi\\rangle =
                \\frac{|\\psi(\\theta+\\tfrac{\\pi}{2}e_i)\\rangle -
                       |\\psi(\\theta-\\tfrac{\\pi}{2}e_i)\\rangle}{2\\sqrt{2}}.

        Parameters
        ----------
        theta : ``ndarray`` of shape ``(n_parameters,)``
            Variational parameters.

        Return
        ----------
        jac : ``ndarray`` of shape ``(2**n_qubits, n_parameters)``
            Complex Jacobian whose ``i``-th column is
            :math:`\\partial|\\psi\\rangle/\\partial\\theta_i`.
        """
        theta = np.asarray(theta, dtype=float).reshape(-1)
        n_params = self._param_count
        dim = 1 << self.n_qubits
        jac = np.zeros((dim, n_params), dtype=complex)
        if n_params == 0:
            return jac
        shift = np.pi / 2.0
        for i in range(n_params):
            tp = theta.copy()
            tm = theta.copy()
            tp[i] += shift
            tm[i] -= shift
            jac[:, i] = (self.get_statevector(tp) - self.get_statevector(tm)) / (2.0 * np.sqrt(2.0))
        return jac

    # ------------------------------------------------------------------ #
    #  Utility                                                           #
    # ------------------------------------------------------------------ #
    def draw(self, theta: np.ndarray | None = None, **kwargs):
        """Draw the parameterised circuit.

        Parameters
        ----------
        theta : ``ndarray``, optional
            Concrete parameters used when drawing.  When ``None`` a zero
            parameter vector is used.
        """
        if theta is None:
            theta = np.zeros(self._param_count)
        prog = self._build_prog(theta)
        try:
            return prog.draw(**kwargs)
        except Exception:
            return prog


class HardwareEfficientAnsatz(VariationalAnsatz):
    """A layered hardware-efficient ansatz that is the identity at ``theta=0``.

    Each layer is composed of

    * a rotation block ``RX(theta)`` followed by ``RZ(theta)`` on every qubit,
      and
    * an entangling block of two-qubit ``RZZ(theta)`` rotations arranged in a
      nearest-neighbour ring.

    Because every parameterised gate reduces to the identity when ``theta=0``,
    the ansatz reproduces the ``init_state`` (or ``|0...0>``) at zero
    parameters, which is the convention expected by the variational Lindblad
    solver.

    Parameters
    ----------
    n_qubits : ``int``
        Number of qubits.
    layers : ``int``, optional (default=1)
        Number of repeated rotation + entangling layers.
    rotations : ``str``, optional (default='rxz')
        Per-qubit rotation pattern.  Supported values are ``'rxz'``,
        ``'ryz'`` and ``'rxryrz'``.
    entangler : ``{'rzz', 'rxx', 'ryy'}``, optional (default='rzz')
        Parameterised two-qubit entangling gate.  ``RZZ(0)=I`` and similarly
        for the other options, which is what guarantees the
        identity-at-zero-parameters property.
    init_state : ``ndarray``, optional
        Computational-basis state the ansatz is initialised in.

    Examples
    --------
    >>> import numpy as np
    >>> from pyqpanda_alg.LindbladMagnus.ansatz import HardwareEfficientAnsatz
    >>> ans = HardwareEfficientAnsatz(n_qubits=3, layers=2)
    >>> sv = ans.get_statevector(np.zeros(ans.n_parameters))
    """

    _ENTANGLERS = {
        "rzz": RZZ,
        "rxx": RXX,
        "ryy": RYY,
    }

    def __init__(self, n_qubits: int, layers: int = 1,
                 rotations: str = "rxz",
                 entangler: str = "rzz",
                 init_state: np.ndarray | None = None):
        super().__init__(n_qubits=n_qubits, init_state=init_state)
        if entangler not in self._ENTANGLERS:
            raise ValueError(
                f"entangler must be one of {list(self._ENTANGLERS)}, got "
                f"{entangler!r}")
        rot_map = {
            "rxz": (RX, RZ),
            "ryz": (RY, RZ),
            "rxryrz": (RX, RY, RZ),
        }
        if rotations not in rot_map:
            raise ValueError(
                f"rotations must be one of {list(rot_map)}, got "
                f"{rotations!r}")
        rot_gates = rot_map[rotations]
        ent_factory = self._ENTANGLERS[entangler]
        for _ in range(int(layers)):
            # Rotation layer: every gate is identity at theta=0.
            for q in range(n_qubits):
                for factory in rot_gates:
                    self.add_gate(factory, q)
            # Entangling layer: parameterised two-qubit gates.  Each of them
            # is identity at theta=0, so the entangling layer is "off" until
            # the variational parameters are turned on.
            for q in range(n_qubits):
                ctrl, tgt = q, (q + 1) % n_qubits
                if ctrl != tgt:
                    self.add_gate(ent_factory, (ctrl, tgt))


def _prepare_state_prog(state: np.ndarray, n_qubits: int) -> QProg:
    """Build a :class:`QProg` that prepares the reference ``state``.

    Only computational-basis states (a single non-zero amplitude) are supported
    through X gates.  This covers every model shipped with the module (FMO,
    TFIM, RPM).  Applications needing an arbitrary superposition as reference
    should prepare it through user-added static gates.

    Parameters
    ----------
    state : ``ndarray``
        Reference statevector, length ``2**n_qubits``.
    n_qubits : ``int``
        Number of qubits.

    Return
    ----------
    prog : :class:`~pyqpanda3.core.QProg`
        Quantum program preparing the requested basis state.

    Raises
    ------
    ValueError
        If ``state`` is not a computational-basis state.  The caller is
        expected to add the necessary preparation gates manually in that case.
    """
    prog = QProg()
    amp = np.asarray(state, dtype=complex).reshape(-1)
    nonzero = np.where(np.abs(amp) > 1e-12)[0]
    if nonzero.size == 1:
        idx = int(nonzero[0])
        for bit in range(n_qubits):
            if (idx >> bit) & 1:
                prog << X(bit)
        return prog
    raise ValueError(
        "init_state must be a computational-basis state (exactly one "
        "non-zero amplitude) to be prepared automatically; got a state "
        f"with {nonzero.size} non-zero amplitudes. Either supply a basis "
        "state or add preparation gates to the ansatz explicitly.")
